name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@v1

    - name: Flyctl auth
      run: flyctl auth login --access-token ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      run: flyctl deploy --config fly.toml --remote-only
